name: Node.js CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with: 
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
      - name: Echo the changed files
        id: changed
        run: |
          a=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.js || $file == *.jsx || $file == *.ts || $file == *.tsx ]]; then
            a="${a} ${file}"
            fi
          done
          echo "changed_file=$a" >> $GITHUB_OUTPUT
      - name: Use pnpm 
        uses: pnpm/action-setup@v2
        with:
          node-version:  '6.0.2'
      - run: pnpm i 
      - run: pnpm run build 
      - run: pnpm run lint -- ${{ steps.changed.outputs.changed_file }} 